### ISSUE TITLE
The audio isn't working.

### ISSUE THREAD

**Issue by AustinTheSuperiorVyonder2021** [weespin/WillFromAfarDownloader#34] opened 2023-07-08 11:16 UTC
I know this is part of the voice generation issue, but somehow, when I press play, the audio doesn't play and when I press download, it downloads the file, but it doesn't come with the words you type in and has zero audio. Can you please fix it right away? 

Oh, and by the way, I tested the mobile app version of Acapela, and it appears to work just fine, so there's no need to worry about the mobile app. It's just the computer version that is having issues.

**Comment by Caramell-Dansen** [comment] 2023-07-08 15:01
Same here.

**Comment by HUXAIFAZAKI** [comment] 2023-07-08 15:20
Same here.

**Comment by ZomkaDEV** [comment] 2023-07-08 18:27
I found out that the server generates a 0.5-second file. I guess they updated how the API works. I'm not sure. :(

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-08 18:35
So that's why the voices aren't generating as they are supposed to. The API got messed with.

**Comment by flasher1101** [comment] 2023-07-09 15:32
When the issue is going to be fixed?

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-09 16:56
Hopefully soon if someone sees this.

**Comment by ZomkaDEV** [comment] 2023-07-09 19:46
> When the issue is going to be fixed?

It will be fixed, when it will be fixed. Everyone has a life outside of their projects.

**Comment by weespin** [comment] 2023-07-10 07:11
Duplicate of https://github.com/weespin/WillFromAfarDownloader/issues/33

**Closed as completed** 2023-07-10 07:12 UTC
