### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by Sheepofthesouth** [weespin/WillFromAfarDownloader#27] opened 2023-01-01 04:34 UTC
i downloaded both the release zip and the willfromafar zip, but unfortunately i cannot run this because everytime i hit play it prompts a pop up saying "unhandled exception"

![Capture](https://user-images.githubusercontent.com/121741817/210161057-eaac13d0-ff79-416e-a527-cdade85d0eea.PNG)

 - OS: windows 11
 - Version 2.3.1

sorry to ask this. I saw someone brought this up a while back but it wasnt actually clearly resolved.

**Comment by weespin** [comment] 2023-01-21 20:35
Please click on "details" and copy whole text here

**Comment by Sheepofthesouth** [comment] 2023-01-25 15:16
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 147.135.223.233:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AcapellaDownloader.Utils.UpdateNonceToken() in C:\Users\Weespin Null\source\repos\WillFromAfarDownloader\AcapellaDownloader\Utils.cs:line 40
   at AcapellaDownloader.Utils.GetSoundLink(String text, String voiceid) in C:\Users\Weespin Null\source\repos\WillFromAfarDownloader\AcapellaDownloader\Utils.cs:line 59
   at AcapellaDownloader.Form1.GetGUISoundLink() in C:\Users\Weespin Null\source\repos\WillFromAfarDownloader\AcapellaDownloader\Form1.cs:line 132
   at AcapellaDownloader.Form1.btnPlay_Click(Object sender, EventArgs e) in C:\Users\Weespin Null\source\repos\WillFromAfarDownloader\AcapellaDownloader\Form1.cs:line 145
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 147.135.223.233:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AcapellaDownloader
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Owner/Downloads/capn/AcapellaDownloader.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4590.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
NAudio
    Assembly Version: 1.10.0.0
    Win32 Version: 1.10.0.0
    CodeBase: file:///C:/Users/Owner/Downloads/capn/NAudio.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by weespin** [comment] 2023-05-01 19:54
This is very strange issue with very low reproduction rate. 
I recommend using a VPN. 
I'll leave this issue open.
If anyone else encounter this issue please leave a comment.

**Comment by Kawaii123456** [comment] 2023-05-02 00:38
> This is very strange issue with very low reproduction rate. I recommend using a VPN. I'll leave this issue open. If anyone else encounter this issue please leave a comment.

i am still having problems, every time i enter a text and click the play button, it crashes, 😔 i count on this thing...

**Comment by weespin** [comment] 2023-05-02 07:53
Please ensure that you're using the last version
https://github.com/weespin/WillFromAfarDownloader/releases/tag/2.3.2

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-10 15:34
Hey dude, 34 was NOT a duplicate of 33. And here's why. One, the unhandled exception thing did NOT pop up, and two, the mobile app itself worked fine. It's just the computer one that doesn't.

**Comment by weespin** [comment] 2023-07-10 15:44
@AustinTheSuperiorVyonder2021
The mobile app is not working on Android 13

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-11 05:24
I'm sorry to say this, but you're wrong in this case because I have Android 13, and The Mobile App actually is working on my end. I did give it a test and I did hear voices from the mobile version. It's the computer version that isn't working since there's an Audio issue with the volume. Not the voices.

**Comment by jtothef** [comment] 2023-07-13 17:40
> I'm sorry to say this, but you're wrong in this case because I have Android 13, and The Mobile App actually is working on my end. I did give it a test and I did hear voices from the mobile version. It's the computer version that isn't working since there's an Audio issue with the volume. Not the voices.

@AustinTheSuperiorVyonder2021 - Does the app only work for voices you have already downloaded, or all voices? If you try to test a voice, I believe that will not work at the moment.

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-13 17:58
I tested all the voices, including the one I tested, and they worked well unlike the computer.

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-21 14:59
@jtothef here is proof that the mobile version does in fact work. 

https://github.com/weespin/WillFromAfarDownloader/assets/89959755/ea94c33d-9fad-47c7-b52f-9262d0011312

**Comment by jtothef** [comment] 2023-07-21 15:56
> @jtothef here is proof that the mobile version does in fact work.
> 
>  Screen_Recording_20230721_085530_Acapela.TTS.Voices.mp4

@AustinTheSuperiorVyonder2021 
You downloaded this voice, those work.

The broken part is on demoing voices that you have not downloaded.
I assume this is the same API call that the GitHub project uses.

**Comment by masterblek93** [comment] 2023-08-06 13:15
After downloading the latest version, I no longer get that error, BUT I can't hear any sound coming from the tts.
I also download blank sound files.
I think switching to a new server was a bad idea.

**Closed as completed** 2024-06-27 23:33 UTC
Labels: bug
