### ISSUE TITLE
The voices don't generate anymore (Do I need to do something?)

### ISSUE THREAD

**Issue by AmethystStar** [weespin/WillFromAfarDownloader#35] opened 2023-07-17 23:20 UTC
Do I need to do something or do I have to wait till the server works again?

**Comment by Kawaii123456** [comment] 2023-07-18 05:43
it's still broken for me, i'm just waiting for it to be fixed, i am sure it will be fixed soon <:)

**Comment by flasher1101** [comment] 2023-07-18 16:58
I'm waiting too. I tried so many voiceovers and strangely enough, acapella voicebox is the best. It has this cool feeling that other don't have for some reason.

**Comment by WaldoAndFriends** [comment] 2023-07-18 21:14
Seems indeed to be broken at the moment.

**Comment by ZomkaDEV** [comment] 2023-07-19 22:43
The API endpoint was changed. There's no fix without changing the code.

I'm working on a program that will work like WillFromAfarDownloader, although I'm not sure if it would work on old versions of Windows (anything under Windows 10 might not work), but maybe I'll rewrite it in another language someday :shrug:

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-20 10:32
If you can do that, it would help. I think this chat is a duplicate of my previous issue opening though.

**Comment by DatDuckSaysQuack** [comment] 2023-07-21 00:20
> The API endpoint was changed. There's no fix without changing the code.
> 
> I'm working on a program that will work like WillFromAfarDownloader, although I'm not sure if it would work on old versions of Windows (anything under Windows 10 might not work), but maybe I'll rewrite it in another language someday 🤷

Please hit us up when you've got something running, I too am interested in seeing this work again

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-21 14:31
I have a hunch someone made a fix that shouldn't have been made.

**Comment by flasher1101** [comment] 2023-07-25 18:43
I want to generate "3 weeks later" meme using one of the voices, but I can't (sarcasm)

**Comment by ZomkaDEV** [comment] 2023-07-25 20:54
> I have a hunch someone made a fix that shouldn't have been made.

The demo had added some background noise when I finished working on the app. It still works but the background noise is annoying. That’s why I haven’t posted an update.

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-07-28 11:08
That's why they use the mobile app. And a suggestion, rather than just letting people download demo voices, they should download from the API of the downloaded voices.

**Comment by WaleedAnimate2020** [comment] 2023-08-03 07:37
It's been more than 3 weeks, and the server is still closed? This is just really disappointing. I have to wait longer until it's completely fixed

**Comment by masterblek93** [comment] 2023-08-06 12:54
Sooo, is the TTS fixed?
I haven't been using the software for months, and now when I need it it's not working. :(

**Comment by flasher1101** [comment] 2023-08-06 13:10
I guess the only way is to pay now. 5$ for 700 characters

**Comment by ZomkaDEV** [comment] 2023-08-06 13:32
> I guess the only way is to pay now. 5$ for 700 characters

The app’s demos don’t even work. I would assume the paid voices don’t too.

**Comment by ZomkaDEV** [comment] 2023-08-06 13:33
> Sooo, is the TTS fixed?
> I haven't been using the software for months, and now when I need it it's not working. :(

It’s an issue with Acapela Group. You can get access to their API but it’s not free.

**Comment by AustinTheSuperiorVyonder2021** [comment] 2023-08-06 13:42
@MrZomka Actually, the paid and downloaded voices do work. It's the demo voices alone that don't. I still have a few working voices myself.

**Comment by flasher1101** [comment] 2023-08-19 17:47
I'm sorry guys for not respoding. Had some really hard days. So my method of using acapela box is recording with obs. Then I use Davinci Resolve voice isolation feature and then I run audio files through Adobe Enhance Speech online to get reed of any artifacts. Actually there are 2 more options to use some acapela voices for free.

**Comment by Kawaii123456** [comment] 2023-08-19 23:04
> 

What are the 2 other options? i'm just Curious. <:)

**Comment by flasher1101** [comment] 2023-08-20 06:54
> > 
> 
> What are the 2 other options? i'm just Curious. <:)

The second option is to use cracked acapela infovox 3 as detailed here https://www.youtube.com/watch?v=VQAWO-6qfzE. But there are not many voices and the quality is worse than in 4 version. And the third option is to use Acapela plugin for NVMA trial version like this: "For anyone complaining about the 30 day trial debacle, here's a complex but simple solution. Use VMWare Workstation, install Windows inside a virtual machine, create a snapshot after Windows is installed and everything is set up the way you want after you have downloaded the setup file for Infovox. Then, install Infovox, and when the trial runs out, revert to the snapshot you saved to and install it again. Since there's no online system used for the trial detection, or tied to an email account, this method works simply because the contents in the Windows registry somewhere in the key of the Infovox keys is the trial expiration information. Without those registry keys, the installation would start as if it was being installed on a new machine, thus resetting the trial."

**Comment by weespin** [comment] 2024-06-27 23:32
Fixed in https://github.com/weespin/WillFromAfarDownloader/commit/78dc6cd4bc42619fe4898c3fd4c9b1da8ee123b3

**Closed as completed by weespin** 2024-06-27 23:32 UTC

**Comment by WaleedAnimate2020** [comment] 2024-06-30 09:19
> Fixed in [78dc6cd](https://github.com/weespin/WillFromAfarDownloader/commit/78dc6cd4bc42619fe4898c3fd4c9b1da8ee123b3)

I added new children voices. Including Dutch ones (Merel and Thijs)
